import { Component } from '@angular/core';
import { NavbarComponent } from '../home/navbar/navbar.component';
import { FooterComponent } from '../home/footer/footer.component';

@Component({
  selector: 'app-champions',
  standalone: true,
  imports: [NavbarComponent, FooterComponent],
  templateUrl: './champions.component.html',
  styleUrl: './champions.component.css',
})
export class ChampionsComponent {
  heavyweightChampions = [
    {
      img: '../../../assets/champions/oleksandr-usyk.webp',
      name: 'Oleksandr Oleksándrovich Usyk',
      age: 37,
      height: '1.90',
      title: 'IBF-IBO-WBA-WBO',
      victory: 21,
      knockout: 14,
      defeat: 0,
      draw: 0,
      wiki: 'https://es.wikipedia.org/wiki/Oleksandr_Usyk',
      boxrec: 'https://boxrec.com/en/box-pro/659772',
    },
    {
      img: '../../../assets/champions/tyson-fury.jpg',
      name: 'Tyson Luke Fury',
      age: 35,
      height: 2.02,
      title: 'WBC',
      victory: 34,
      knockout: 24,
      defeat: 0,
      draw: 1,
      wiki: 'https://es.wikipedia.org/wiki/Tyson_Fury',
      boxrec: 'https://boxrec.com/en/proboxer/479205',
    },
    {
      img: '../../../assets/champions/manuel-charr.jpg',
      name: 'Mahmoud Omeirat Charr',
      age: 39,
      height: 1.92,
      title: 'WBA',
      victory: 34,
      knockout: 20,
      defeat: 4,
      draw: 0,
      wiki: 'https://en.wikipedia.org/wiki/Mahmoud_Charr',
      boxrec: 'https://boxrec.com/en/box-pro/314362',
    },
    {
      img: '../../../assets/champions/zhilei-zhang.jpg',
      name: 'Zhang Zhilei',
      age: 40,
      height: 1.98,
      title: 'WB0',
      victory: 26,
      knockout: 21,
      defeat: 1,
      draw: 1,
      wiki: 'https://es.wikipedia.org/wiki/Zhang_Zhilei',
      boxrec: 'https://boxrec.com/en/proboxer/479205',
    },
  ];

  cruiserweightChampions = [
    {
      boxer: 'Arsen Goulamirian',
      img: '../../../assets/champions/arsen-goulamirian.png',
      nickname: 'Feroz',
      name: 'Arsen Goulamirian',
      age: 36,
      height: 1.86,
      title: 'WBA',
      victory: 27,
      knockout: 19,
      defeat: 0,
      draw: 0,
      wiki: 'https://en.wikipedia.org/wiki/Arsen_Goulamirian',
      boxrec: 'https://boxrec.com/en/box-pro/572144',
    },
    {
      boxer: 'Norair Mikaeljan',
      img: '../../../assets/champions/Noel-Mikaelyan.jpg',
      name: 'Norair Mikaeljan',
      age: 33,
      height: 1.92,
      title: 'WBC',
      victory: 27,
      knockout: 12,
      defeat: 2,
      draw: 0,
      wiki: 'https://en.wikipedia.org/wiki/Noel_Mikaelian',
      boxrec: 'https://boxrec.com/en/proboxer/571652',
    },
    {
      boxer: 'Chris Billam-Smith',
      img: '../../../assets/champions/chris-billam-smith.jpg',
      name: 'Chris Billam-Smith',
      age: 33,
      height: 1.91,
      title: 'WBO',
      victory: 19,
      knockout: 13,
      defeat: 1,
      draw: 0,
      wiki: 'https://en.wikipedia.org/wiki/Chris_Billam-Smith',
      boxrec: 'https://boxrec.com/en/box-pro/811275',
    },
  ];

  lightheavyweightChampions = [
    {
      boxer: 'Dmitry Bivol',
      img: '../../../assets/champions/dmitri-bivol.webp',
      name: 'Dmitry Yuryevich Bivol',
      age: 33,
      height: 1.83,
      title: 'IBO-WBA',
      victory: 22,
      knockout: 11,
      defeat: 0,
      draw: 0,
      wiki: 'https://es.wikipedia.org/wiki/Dmitry_Bivol',
      boxrec: 'https://boxrec.com/en/box-pro/703924',
    },
    {
      boxer: 'Artur Beterbiyev',
      img: '../../../assets/champions/artur-beterbiev.jpg',
      name: 'Artur Asilbekovich Beterbiev',
      age: 39,
      height: 1.82,
      title: 'IBC-WBC-WBO',
      victory: 20,
      knockout: 20,
      defeat: 0,
      draw: 0,
      wiki: 'https://es.wikipedia.org/wiki/Artur_Beterbiyev',
      boxrec: 'https://boxrec.com/en/box-pro/646981',
    },
  ];

  SuperMiddleweightChampions = [
    {
      boxer: 'Saúl Álvarez',
      img: '../../../assets/champions/saul-alvarez.jpg',
      name: 'Santos Saúl Álvarez Barragán',
      age: 33,
      height: 1.73,
      title: 'IBF-WBA-WBC-WBO',
      victory: 60,
      knockout: 39,
      defeat: 2,
      draw: 0,
      wiki: 'https://es.wikipedia.org/wiki/Saúl_Álvarez',
      boxrec: 'https://boxrec.com/en/box-pro/348759',
    },
    {
      boxer: 'David Morrell',
      img: '../../../assets/champions/david-morrel.jpg',
      name: 'Osvary David Morrell Gutierrez Jr.',
      age: 26,
      height: 1.85,
      title: 'WBA',
      victory: 10,
      knockout: 9,
      defeat: 0,
      draw: 0,
      wiki: 'https://en.wikipedia.org/wiki/David_Morrell_(boxer)',
      boxrec: 'https://boxrec.com/en/box-pro/852450',
    },
    {
      boxer: 'David Benavidez',
      img: '../../../assets/champions/david-benavidez.webp',
      name: 'Anthony David Benavidez',
      age: 27,
      height: 1.88,
      title: 'WBC',
      victory: 28,
      knockout: 24,
      defeat: 0,
      draw: 0,
      wiki: 'https://en.wikipedia.org/wiki/David_Benavidez',
      boxrec: 'https://boxrec.com/en/box-pro/672259',
    },
  ];
}
